language: php
php:
  - 5.3.3
  - 5.4
branches:
  only:
    - 7.x
env:
  - FEDORA_VERSION="3.5"
  - FEDORA_VERSION="3.6.2"
  - FEDORA_VERSION="3.7.0"
before_install:
  - cd $HOME
  - git clone -b 7.x git://github.com/Islandora/islandora.git
  - git clone -b 7.x git://github.com/Islandora/islandora_paged_content.git
  - git clone -b 7.x git://github.com/Islandora/islandora_solution_pack_collection.git
  - git clone -b 7.x git://github.com/Islandora/islandora_solution_pack_large_image.git
  - git clone -b 7.x git://github.com/Islandora/islandora_ocr.git
  - git clone -b 7.x git://github.com/Islandora/islandora_solr_search.git
  - export ISLANDORA_DIR=$HOME/islandora
  - $HOME/islandora/tests/scripts/travis_setup.sh
  - sudo sh $TRAVIS_BUILD_DIR/tests/scripts/adore.sh
  - sudo sh $TRAVIS_BUILD_DIR/tests/scripts/tesseract.sh
  - cd $HOME/drupal-*
  - ln -s $TRAVIS_BUILD_DIR sites/all/modules/emicdora
  - ln -s $HOME/islandora_paged_content sites/all/modules/islandora_paged_content
  - ln -s $HOME/islandora_solution_pack_collection sites/all/modules/islandora_solution_pack_collection
  - ln -s $HOME/islandora_ocr sites/all/modules/islandora_ocr
  - ln -s $HOME/islandora_solution_pack_large_image sites/all/modules/islandora_solution_pack_large_image
  - ln -s $HOME/islandora_solr_search sites/all/modules/islandora_solr_search
  - drush dl imagemagick
  - drush en --user=1 --yes islandora_ocr islandora_large_image imagemagick emicdora islandora_basic_collection islandora_solr
  - drush vset islandora_ocr_tesseract `which tesseract`
script:
  - ant -buildfile sites/all/modules/emicdora/build.xml lint
  - $ISLANDORA_DIR/tests/scripts/line_endings.sh sites/all/modules/emicdora
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer emicdora emicdora_sample collation tei_editor
  - phpcpd --names *.module,*.inc,*.test sites/all/modules/emicdora
  - drush test-run --user=1 --uri=http://localhost:8081 "Emicdora"
